[[zed]]
arch = "aarch64"
git-tree-sha1 = "da195ccfae59f1893861f9d114673aa41f37716e"
os = "macos"

    [[zed.download]]
    sha256 = "046d05b806bf2c44f70bdf3bc53ee6c1bf12e66fdad7abff378a8ecf2a49ed3d"
    url = "https://github.com/JuliaBinaryWrappers/zed_jll.jl/releases/download/zed-v1.14.0+0/zed.v1.14.0.aarch64-apple-darwin.tar.gz"
[[zed]]
arch = "aarch64"
git-tree-sha1 = "05e2a718e7b869ac59e2596cf8528f9c3d2e79f6"
libc = "glibc"
os = "linux"

    [[zed.download]]
    sha256 = "1cf01efa68465b85729069e8853e77e4f3e19920cc2108d270a9f4b97fa15b28"
    url = "https://github.com/JuliaBinaryWrappers/zed_jll.jl/releases/download/zed-v1.14.0+0/zed.v1.14.0.aarch64-linux-gnu.tar.gz"
[[zed]]
arch = "aarch64"
git-tree-sha1 = "05e2a718e7b869ac59e2596cf8528f9c3d2e79f6"
libc = "musl"
os = "linux"

    [[zed.download]]
    sha256 = "1cf01efa68465b85729069e8853e77e4f3e19920cc2108d270a9f4b97fa15b28"
    url = "https://github.com/JuliaBinaryWrappers/zed_jll.jl/releases/download/zed-v1.14.0+0/zed.v1.14.0.aarch64-linux-musl.tar.gz"
[[zed]]
arch = "powerpc64le"
git-tree-sha1 = "bdcf36049e2c2386383fbc9686cf4db210eed2d0"
libc = "glibc"
os = "linux"

    [[zed.download]]
    sha256 = "478c4b357d6d35a5389f8937ee09199b29df4613a7b3bd6c43fe71b475d5d04d"
    url = "https://github.com/JuliaBinaryWrappers/zed_jll.jl/releases/download/zed-v1.14.0+0/zed.v1.14.0.powerpc64le-linux-gnu.tar.gz"
[[zed]]
arch = "x86_64"
git-tree-sha1 = "bf9ee4e075c431e9c0be7b068a4474b607cea6ae"
os = "macos"

    [[zed.download]]
    sha256 = "45949a1655022b8a26eca1e21093f0d944e3869e19d9d4b0039f1c9ec95cd889"
    url = "https://github.com/JuliaBinaryWrappers/zed_jll.jl/releases/download/zed-v1.14.0+0/zed.v1.14.0.x86_64-apple-darwin.tar.gz"
[[zed]]
arch = "x86_64"
git-tree-sha1 = "a7fac5b6a7517e309db105c306f0b70d77b892a0"
libc = "glibc"
os = "linux"

    [[zed.download]]
    sha256 = "39843f0ce4378667672c454f46222172c53b0871a94827ef5eccb6f47f6b9ae1"
    url = "https://github.com/JuliaBinaryWrappers/zed_jll.jl/releases/download/zed-v1.14.0+0/zed.v1.14.0.x86_64-linux-gnu.tar.gz"
[[zed]]
arch = "x86_64"
git-tree-sha1 = "9aea01ff760913e820f8b5d476eb769bf191fcb3"
libc = "musl"
os = "linux"

    [[zed.download]]
    sha256 = "616e379963ea54e8c95dd08f2e7c30c2146b5dfcfa0a397b0da064b20360bd19"
    url = "https://github.com/JuliaBinaryWrappers/zed_jll.jl/releases/download/zed-v1.14.0+0/zed.v1.14.0.x86_64-linux-musl.tar.gz"
[[zed]]
arch = "x86_64"
git-tree-sha1 = "d15f8e06dd07d5c79f2a7eb76190c991c4485769"
os = "freebsd"

    [[zed.download]]
    sha256 = "d5b8ae53dd2dcf970e77a36e1bda194c3a3ceb437ad38b9eef60199e389a3d69"
    url = "https://github.com/JuliaBinaryWrappers/zed_jll.jl/releases/download/zed-v1.14.0+0/zed.v1.14.0.x86_64-unknown-freebsd.tar.gz"
[[zed]]
arch = "x86_64"
git-tree-sha1 = "01540118b7db06d4259102abf5c4b2b3f8571026"
os = "windows"

    [[zed.download]]
    sha256 = "be9aaedec2d1d0df78404fdac8b7b69fef44a89cf11d19b189989675e23e2d8f"
    url = "https://github.com/JuliaBinaryWrappers/zed_jll.jl/releases/download/zed-v1.14.0+0/zed.v1.14.0.x86_64-w64-mingw32.tar.gz"
