# Autogenerated wrapper script for zed_jll for x86_64-w64-mingw32
export zed

JLLWrappers.@generate_wrapper_header("zed")
JLLWrappers.@declare_executable_product(zed)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        zed,
        "bin\\zed.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
